```mermaid
flowchart TB
  Internet((Internet))

  subgraph Region[eu-west-2 London]
    subgraph VPC[acme-dev-network-vpc 10.10.0.0/16]
      IGW[Internet Gateway: acme-dev-network-igw]

      subgraph AZA[eu-west-2a]
        PubA[Public Subnet 10.10.0.0/24 public-euw2a]
        PrivA[Private Subnet 10.10.10.0/24 private-euw2a]
        NAT[NAT Gateway: acme-dev-network-nat-euw2a]
      end

      subgraph AZB[eu-west-2b]
        PubB[Public Subnet 10.10.1.0/24 public-euw2b]
        PrivB[Private Subnet 10.10.11.0/24 private-euw2b]
      end

      ALB[ALB: acme-dev-ecs-alb-public HTTP 80]
      TG[Target Group IP: acme-dev-ecs-tg-http HC /]
      ECS[ECS Service Fargate: acme-dev-ecs-svc-web]
      CW[(CloudWatch Logs)]
    end
  end

  Internet -->|HTTP 80| ALB
  ALB --> TG
  TG --> ECS
  ECS -->|egress| NAT
  NAT --> IGW
  IGW --> Internet
  ECS --> CW