flowchart TB
Internet((Internet))

subgraph Region[eu-west-2 (London)]
  subgraph VPC[acme-dev-network-vpc<br/>10.10.0.0/16]
    IGW[Internet Gateway<br/>acme-dev-network-igw]

    subgraph AZA[eu-west-2a]
      PubA[Public Subnet<br/>10.10.0.0/24<br/>...public-euw2a]
      PrivA[Private Subnet<br/>10.10.10.0/24<br/>...private-euw2a]
      NAT[NAT Gateway<br/>acme-dev-network-nat-euw2a]
    end

    subgraph AZB[eu-west-2b]
      PubB[Public Subnet<br/>10.10.1.0/24<br/>...public-euw2b]
      PrivB[Private Subnet<br/>10.10.11.0/24<br/>...private-euw2b]
    end

    ALB[Application Load Balancer<br/>acme-dev-ecs-alb-public<br/>Listener: HTTP 80]
    TG[Target Group (IP)<br/>acme-dev-ecs-tg-http<br/>HC: /]
    ECS[ECS Service (Fargate)<br/>acme-dev-ecs-svc-web<br/>2 tasks across AZs]
    CW[(CloudWatch Logs)]
  end
end

Internet -->|HTTP:80| ALB
ALB --> TG
TG --> ECS

ECS -->|egress| NAT
NAT --> IGW
IGW --> Internet

ECS --> CW

classDef sg stroke-dasharray: 5 5;
